name: Build in Ubuntu

on:
  workflow_call:
    inputs:
      namespace:
        type: string
        required: true
      artifact_name:
        type: string
        default: senscord
        required: true
jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          repository: SonySemiconductorSolutions/senscord
          ref: ${{ inputs.project_ref }}

      - name: Build in the devcontainer
        uses: devcontainers/ci@v0.3
        with:
          configFile: .devcontainer/ubuntu/devcontainer.json
          push: never
          runCmd: |
            set -euo pipefail
            mkdir build
            cd build
            cmake ../
            cmake --build . --parallel $(nproc) --verbose
